theme: jekyll-theme-slate
title: Hello! Welkome to the Nataly06's page
description: Feel free to bookmark this to keep an eye on my project updates
My ivent - https://calendar.google.com/event?action=TEMPLATE&tmeid=MDNxMm01bjNqMHBpM2dyOWFpbWdwb3YzYnJfMjAxODA2MjdUMDQwMDAwWiAxNW5hdGFsb2Noa2EwNkBt&tmsrc=15natalochka06%40gmail.com&scp=ALL
My interrogation - https://docs.google.com/forms/d/1pygTDRwSwOXr8TQ74NCbmElKlIoY6AE4Y1VyAh0XH4I/edit
